
version: '2.2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.0
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512M -Xmx512M"
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - network.host=0.0.0.0
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - esnet
    ports:
      - 9200:9200
      - 9300:9300

  indexer:
    build: ./backend/elastic
    container_name: elastic-indexer
    depends_on:
      - elasticsearch
    networks:
      - esnet
    command: ./utility/wait-for elasticsearch:9200 -t 500 -- python importer.py --host elasticsearch --local ./data --offline 64
    volumes:
      - ./backend/data:/elastic-import/data

  ner:
      build: ./backend/ner
      container_name: ner
      depends_on:
        - elasticsearch
      command: gunicorn --timeout 200 --workers 3 -b 0.0.0.0:9301 ner_server:app
      volumes:
        # ¯\_(ツ)_/¯
        - ./backend/data:/data # ¯\_(ツ)_/¯
        # ¯\_(ツ)_/¯
      ports:
        - 9301:9301

  webapp:
    container_name: webapp
    build: ./webapp
    networks:
    - esnet
    ports:
    - 3000:80

volumes:
  esdata:
    driver: local

networks:
  esnet:

