
version: '2.2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.0
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512M -Xmx512M"
      - http.cors.enabled=true
      - http.cors.allow-origin=*
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - esnet
    ports:
      - 9200:9200

  webapp:
    container_name: webapp
    build: ./webapp
    networks:
    - esnet
    ports:
    - 3000:80
  # indexer:
  #   build: ./elastic
  #   container_name: elastic-indexer
  #   environment:
  #     - indexer.threads=32
  #   depends_on:
  #     - elasticsearch
  #   networks:
  #     - esnet
  #   command: sh -c 'python importer.py 64'


volumes:
  esdata:
    driver: local

networks:
  esnet:

