version: '2.2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.0
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512M -Xmx512M"
      - http.cors.enabled=true
      - http.cors.allow-origin=*
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - esnet
    ports:
      - 9200:9200
  indexer:
    build: ./elastic
    container_name: elastic-indexer
    depends_on:
      - elasticsearch
    networks:
      - esnet
    command: python importer.py --host elasticsearch --local ./data --offline 64
    volumes:
      - ./data:/elastic-import/data
    
    
volumes:
  esdata:
    driver: local

networks:
  esnet: